### ISSUE TITLE
TextDecoder support for node 10

### ISSUE THREAD

**Issue by nduchak** [libp2p/js-peer-id#144]
```
/home/circleci/project/node_modules/peer-id/node_modules/multihashes/node_modules/multibase/src/util.js:3
const textDecoder = new TextDecoder()
                    ^
ReferenceError: TextDecoder is not defined
    at Object.<anonymous> (/home/circleci/project/node_modules/peer-id/node_modules/multihashes/node_modules/multibase/src/util.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module.replacementCompile (/home/circleci/project/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.<anonymous> (/home/circleci/project/node_modules/append-transform/index.js:62:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

Error when using on Node v10

**Comment by vasco-santos** [comment]
Hello @nduchak 

Thanks for reporting this. It is true that TextDecoder is only available since node11. We are working towards supporting [Active LTS](https://nodejs.org/en/about/releases) node versions to enable us to provide a better library with a smaller bundle. This way, we are not supporting node 10 anymore.

**Comment by nduchak** [comment]
Thanks for quick  response. Seems its works for me for node 12 and 14
